### ISSUE TITLE
backend: serve testnet ledger data

### ISSUE THREAD

**Issue by acharb** [stellar/dashboard#214]
figma design for dashboard v2: https://www.figma.com/file/4z9lsHvbsEoVAtzfj3mNzy/Stellar-Dashboard?node-id=206%3A808

the testnet page has aggregated ledger info, which isn't currently served from the backend (right now it's just mainnet on the backend)

**Comment by Selhar** [comment]
Hey, what is the expected behavior here? Should we permanently listen for updates both on testnet and mainnet, or only fetch testnet data once it's requested and not listen for new requests?

If it's the former, i'll start this task from the dex branch, since we need to change all redis variables to have a _testnet namespace.

**Comment by acharb** [comment]
>  Should we permanently listen for updates both on testnet and mainnet

yup this one 👍

> If it's the former, i'll start this task from the dex branch, since we need to change all redis variables to have a _testnet namespace.

whichever branch is easiest sgtm, just to be clear though we don't need dex data for testnet (you can see on the figma designs Dex data is only for mainnet)

**Comment by Selhar** [comment]
Solved by #283
